// <auto-generated />
using System;
using Expense_Tracker_Application.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Expense_Tracker_Application.Migrations
{
    [DbContext(typeof(ExpenseTrackerDbContext))]
    partial class ExpenseTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Expense_Tracker_Application.Models.DailyExpense", b =>
                {
                    b.Property<int>("DailyExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("money");

                    b.Property<int>("ExpenseCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("date");

                    b.HasKey("DailyExpenseId");

                    b.HasIndex("ExpenseCategoryId");

                    b.ToTable("DailyExpenses");

                    b.HasData(
                        new
                        {
                            DailyExpenseId = 1,
                            Amount = 4000.00m,
                            ExpenseCategoryId = 1,
                            ExpenseDate = new DateTime(2021, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DailyExpenseId = 2,
                            Amount = 5000.00m,
                            ExpenseCategoryId = 2,
                            ExpenseDate = new DateTime(2021, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DailyExpenseId = 3,
                            Amount = 6000.00m,
                            ExpenseCategoryId = 3,
                            ExpenseDate = new DateTime(2021, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DailyExpenseId = 4,
                            Amount = 7000.00m,
                            ExpenseCategoryId = 4,
                            ExpenseDate = new DateTime(2021, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DailyExpenseId = 5,
                            Amount = 8000.00m,
                            ExpenseCategoryId = 5,
                            ExpenseDate = new DateTime(2021, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DailyExpenseId = 6,
                            Amount = 3000.00m,
                            ExpenseCategoryId = 6,
                            ExpenseDate = new DateTime(2021, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Expense_Tracker_Application.Models.ExpenseCategory", b =>
                {
                    b.Property<int>("ExpenseCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("ExpenseCategoryId");

                    b.ToTable("ExpenseCategories");

                    b.HasData(
                        new
                        {
                            ExpenseCategoryId = 1,
                            CategoryName = "House Rent"
                        },
                        new
                        {
                            ExpenseCategoryId = 2,
                            CategoryName = "Water Bill"
                        },
                        new
                        {
                            ExpenseCategoryId = 3,
                            CategoryName = "Electric Bill"
                        },
                        new
                        {
                            ExpenseCategoryId = 4,
                            CategoryName = "Groceries"
                        },
                        new
                        {
                            ExpenseCategoryId = 5,
                            CategoryName = "Uber"
                        },
                        new
                        {
                            ExpenseCategoryId = 6,
                            CategoryName = "Medications"
                        });
                });

            modelBuilder.Entity("Expense_Tracker_Application.Models.DailyExpense", b =>
                {
                    b.HasOne("Expense_Tracker_Application.Models.ExpenseCategory", "ExpenseCategory")
                        .WithMany("DailyExpenses")
                        .HasForeignKey("ExpenseCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseCategory");
                });

            modelBuilder.Entity("Expense_Tracker_Application.Models.ExpenseCategory", b =>
                {
                    b.Navigation("DailyExpenses");
                });
#pragma warning restore 612, 618
        }
    }
}
